header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Koushik Mondal (github.com/raptar231)
    copyright-year: '2024-2026'

  paths-ignore:
    - 'dist'
    - 'build'
    - '*.egg-info'
    - '.venv'
    - '__pycache__'
    - '.pytest_cache'
    - '.mypy_cache'
    - '.ruff_cache'
    - '*.md'
    - 'LICENSE'
    - '.github'
    - 'tests/fixtures'

  comment: on-failure